#!/usr/bin/env python3
"""Q19 — typecheck enforcement against committed mypy + tsc baselines.

Five rules:
  Q19.new-typecheck-finding     — mypy/tsc reports a finding NOT in the baseline.
  Q19.baseline-schema-violation — baseline file is neither a JSON array nor an
                                   object containing a `violations` array of
                                   {file, line, code, message} entries.
  Q19.baseline-grew-without-adr — git diff shows additions to a baseline AND
                                   no docs/decisions/<date>-*.md is staged.
  Q19.mypy-config-missing       — declared mypy strict module path absent.
  Q19.tsc-config-missing        — frontend/tsconfig.json missing strict.

Modes:
  default                  — run mypy+tsc, diff vs baseline, ERROR on new findings.
  --replay-output {mypy|tsc} — read --target as recorded tool output (test bypass).
  --validate-baseline-only  — only schema-validate --target; skip mypy/tsc.
  --regen-baseline          — overwrite baselines via tools/generate_typecheck_baseline.py.

H-25:
  Missing input    — exit 2 if --target needed but absent.
  Malformed input  — WARN harness.unparseable when fixture file unreadable.
  Upstream failed  — mypy/tsc binary missing → WARN Q19.upstream-tool-missing.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / ".harness/checks"))

from _common import emit  # noqa: E402

DEFAULT_POLICY = REPO_ROOT / ".harness" / "typecheck_policy.yaml"
DEFAULT_MYPY_BASELINE = REPO_ROOT / ".harness" / "baselines" / "mypy_baseline.json"
DEFAULT_TSC_BASELINE = REPO_ROOT / ".harness" / "baselines" / "tsc_baseline.json"

MYPY_LINE_RE = re.compile(
    r'^(?P<file>[^:]+):(?P<line>\d+):(?:\d+:)?\s+error:\s+'
    r'(?P<msg>.+?)\s+\[(?P<code>[^\]]+)\]\s*$'
)
TSC_LINE_RE = re.compile(
    r'^(?P<file>[^()]+)\((?P<line>\d+),\d+\):\s+error\s+'
    r'(?P<code>TS\d+):\s+(?P<msg>.+?)\s*$'
)


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _coerce_baseline_entries(data: object) -> list[dict] | None:
    """Accept either a plain JSON array or `{violations: [...]}` shape."""
    if isinstance(data, list):
        return data
    if isinstance(data, dict) and isinstance(data.get("violations"), list):
        return data["violations"]
    return None


def _load_baseline_file(path: Path) -> list[dict]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    coerced = _coerce_baseline_entries(data)
    return coerced or []


def _normalize_tsc_entry(entry: dict) -> dict:
    """tsc baselines (generated by tools/generate_typecheck_baseline.py) use
    paths relative to frontend/; tsc invoked from REPO_ROOT emits paths
    starting with frontend/. Reconcile by prepending frontend/ when needed.
    Also normalize integer codes to TS<n> string form."""
    out = dict(entry)
    file_str = str(out.get("file", ""))
    if file_str and not file_str.startswith("frontend/"):
        out["file"] = f"frontend/{file_str}"
    code = out.get("code")
    if isinstance(code, int):
        out["code"] = f"TS{code}"
    return out


def _validate_baseline_schema(path: Path) -> int:
    """Validate one baseline file. Returns count of ERROR findings emitted."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        emit("ERROR", path, "Q19.baseline-schema-violation",
             f"baseline JSON parse failed: {exc}",
             "re-generate via `make harness-typecheck-baseline`", line=1)
        return 1
    entries = _coerce_baseline_entries(data)
    if entries is None:
        emit("ERROR", path, "Q19.baseline-schema-violation",
             f"baseline must be a JSON array or object with `violations` array, got {type(data).__name__}",
             "re-generate via `make harness-typecheck-baseline`", line=1)
        return 1
    required = {"file", "line", "code", "message"}
    errors = 0
    for idx, entry in enumerate(entries):
        if not isinstance(entry, dict):
            emit("ERROR", path, "Q19.baseline-schema-violation",
                 f"entry [{idx}] is not an object",
                 "re-generate via `make harness-typecheck-baseline`", line=1)
            errors += 1
            continue
        missing = required - set(entry.keys())
        if missing:
            emit("ERROR", path, "Q19.baseline-schema-violation",
                 f"entry [{idx}] missing keys: {sorted(missing)}",
                 "re-generate via `make harness-typecheck-baseline`", line=1)
            errors += 1
    return errors


def _parse_findings(text: str, tool: str) -> list[dict]:
    pattern = MYPY_LINE_RE if tool == "mypy" else TSC_LINE_RE
    out: list[dict] = []
    for line in text.splitlines():
        m = pattern.match(line.strip())
        if not m:
            continue
        out.append({
            "file": m.group("file").strip(),
            "line": int(m.group("line")),
            "code": m.group("code").strip(),
            "message": m.group("msg").strip(),
        })
    return out


def _signature(entry: dict) -> tuple[str, int, str, str]:
    return (
        str(entry.get("file", "")),
        int(entry.get("line", 0)),
        str(entry.get("code", "")),
        str(entry.get("message", "")),
    )


def _diff_against_baseline(found: list[dict], baseline: list[dict]) -> list[dict]:
    baseline_sigs = {_signature(b) for b in baseline}
    return [f for f in found if _signature(f) not in baseline_sigs]


def _run_subprocess(cmd: list[str]) -> tuple[bool, str]:
    """Returns (succeeded, output). succeeded=False if binary missing."""
    binary = cmd[0]
    if not shutil.which(binary):
        if binary == "npx" and shutil.which("node"):
            pass
        else:
            return False, ""
    try:
        result = subprocess.run(
            cmd, cwd=REPO_ROOT, capture_output=True, text=True, timeout=120,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False, ""
    return True, (result.stdout or "") + (result.stderr or "")


def _run_mypy(policy: dict) -> tuple[bool, str]:
    paths = policy.get("mypy_strict_paths") or [
        "backend/src/storage", "backend/src/learning",
        "backend/src/models", "backend/src/api", "backend/src/agents",
    ]
    return _run_subprocess(["mypy", "--strict", *paths])


def _run_tsc() -> tuple[bool, str]:
    return _run_subprocess([
        "npx", "--prefix", "frontend", "tsc",
        "--noEmit", "-p", "frontend/tsconfig.json",
    ])


def _check_baseline_growth_requires_adr() -> int:
    if not shutil.which("git"):
        return 0
    try:
        diff = subprocess.run(
            ["git", "diff", "--name-only", "HEAD"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return 0
    changed = [p for p in diff.stdout.splitlines() if p.strip()]
    baseline_changed = [
        p for p in changed
        if p.startswith(".harness/baselines/") and (
            p.endswith("mypy_baseline.json") or p.endswith("tsc_baseline.json")
        )
    ]
    if not baseline_changed:
        return 0
    new_adrs = [
        p for p in changed
        if p.startswith("docs/decisions/") and not p.endswith("_TEMPLATE.md")
    ]
    if new_adrs:
        return 0
    emit("ERROR", Path(baseline_changed[0]), "Q19.baseline-grew-without-adr",
         f"typecheck baseline changed ({baseline_changed}) without an ADR",
         "add docs/decisions/<YYYY-MM-DD>-baseline-growth.md justifying the new entries",
         line=0)
    return 1


def _scan_default(policy_path: Path) -> int:
    policy = _load_yaml(policy_path)
    errors = 0

    for path in (DEFAULT_MYPY_BASELINE, DEFAULT_TSC_BASELINE):
        if path.exists():
            errors += _validate_baseline_schema(path)

    ok, output = _run_mypy(policy)
    if not ok:
        emit("WARN", Path("mypy"), "Q19.upstream-tool-missing",
             "mypy binary not installed; typecheck-diff skipped",
             "install mypy (Sprint H.0b Story 12)", line=0)
    else:
        baseline = _load_baseline_file(DEFAULT_MYPY_BASELINE)
        for entry in _diff_against_baseline(_parse_findings(output, "mypy"), baseline):
            emit("ERROR", Path(entry["file"]), "Q19.new-typecheck-finding",
                 f"mypy {entry['code']}: {entry['message']}",
                 "fix the type error or re-baseline (requires ADR per Q15)",
                 line=entry["line"])
            errors += 1

    ok, output = _run_tsc()
    if not ok:
        emit("WARN", Path("tsc"), "Q19.upstream-tool-missing",
             "tsc binary not installed; typecheck-diff skipped",
             "install TypeScript (Sprint H.0b Story 12)", line=0)
    else:
        baseline = [_normalize_tsc_entry(e) for e in _load_baseline_file(DEFAULT_TSC_BASELINE)]
        for entry in _diff_against_baseline(_parse_findings(output, "tsc"), baseline):
            emit("ERROR", Path(entry["file"]), "Q19.new-typecheck-finding",
                 f"tsc {entry['code']}: {entry['message']}",
                 "fix the type error or re-baseline (requires ADR per Q15)",
                 line=entry["line"])
            errors += 1

    errors += _check_baseline_growth_requires_adr()
    return errors


def _scan_replay(target: Path, tool: str, baseline_path: Path) -> int:
    try:
        text = target.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        emit("WARN", target, "harness.unparseable",
             f"could not read {target}: {exc}",
             "check file path", line=1)
        return 0
    baseline = _load_baseline_file(baseline_path)
    errors = 0
    for entry in _diff_against_baseline(_parse_findings(text, tool), baseline):
        emit("ERROR", Path(entry["file"]), "Q19.new-typecheck-finding",
             f"{tool} {entry['code']}: {entry['message']}",
             "fix the type error or re-baseline (requires ADR per Q15)",
             line=entry["line"])
        errors += 1
    return errors


def _regen_baseline() -> int:
    """Delegate to the existing tools/generate_typecheck_baseline.py."""
    script = REPO_ROOT / "tools" / "generate_typecheck_baseline.py"
    if not script.exists():
        emit("WARN", script, "Q19.upstream-tool-missing",
             "generator script missing; cannot regenerate baselines",
             "restore tools/generate_typecheck_baseline.py", line=0)
        return 1
    result = subprocess.run(
        [sys.executable, str(script)],
        cwd=REPO_ROOT, capture_output=False,
    )
    return result.returncode


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint: dispatch to schema/replay/regen/default modes."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", type=Path)
    parser.add_argument("--policy", type=Path, default=DEFAULT_POLICY)
    parser.add_argument("--baseline", type=Path)
    parser.add_argument("--replay-output", choices=["mypy", "tsc"])
    parser.add_argument("--validate-baseline-only", action="store_true")
    parser.add_argument("--regen-baseline", action="store_true")
    parser.add_argument("--pretend-path", type=str)
    args = parser.parse_args(argv)

    if args.regen_baseline:
        return _regen_baseline()

    if args.validate_baseline_only:
        if args.target is None:
            emit("ERROR", Path("--target"), "harness.target-missing",
                 "--validate-baseline-only requires --target <baseline.json>",
                 "pass --target path/to/baseline.json", line=0)
            return 2
        return 1 if _validate_baseline_schema(args.target) else 0

    if args.replay_output:
        if args.target is None:
            emit("ERROR", Path("--target"), "harness.target-missing",
                 "--replay-output requires --target <recorded-output.txt>",
                 "pass --target path/to/recorded.txt", line=0)
            return 2
        baseline = args.baseline or (
            DEFAULT_MYPY_BASELINE if args.replay_output == "mypy"
            else DEFAULT_TSC_BASELINE
        )
        return 1 if _scan_replay(args.target, args.replay_output, baseline) else 0

    return 1 if _scan_default(args.policy) else 0


if __name__ == "__main__":
    sys.exit(main())
