import React, { useMemo, useCallback } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { V4Session, DiagnosticPhase } from '../../types';
import { listSessionsV4, getSessionDossier } from '../../services/api';
import { ActivityFeedRow } from '../shared';
import type { SystemStatus } from '../shared';

interface LiveIntelligenceFeedProps {
  onSelectSession: (session: V4Session) => void;
  filterActive?: boolean;
}

const phaseToStatus = (phase: DiagnosticPhase): { status: SystemStatus; label: string } => {
  if (['initial', 'collecting_context'].includes(phase)) return { status: 'in_progress', label: 'Collecting' };
  if (['logs_analyzed', 'metrics_analyzed', 'k8s_analyzed', 'tracing_analyzed', 'code_analyzed'].includes(phase)) return { status: 'in_progress', label: 'Analyzing' };
  if (['validating', 're_investigating'].includes(phase)) return { status: 'in_progress', label: 'Validating' };
  if (phase === 'fix_in_progress') return { status: 'degraded', label: 'Remediating' };
  if (['diagnosis_complete', 'complete'].includes(phase)) return { status: 'healthy', label: 'Resolved' };
  if (phase === 'error') return { status: 'critical', label: 'Error' };
  return { status: 'unknown', label: String(phase) };
};

const capabilityAgents = (cap?: string): string[] => {
  switch (cap) {
    case 'troubleshoot_app': return ['Log', 'Metric', 'Trace', 'Code'];
    case 'pr_review': return ['Code', 'Security'];
    case 'github_issue_fix': return ['Code', 'Patch'];
    case 'cluster_diagnostics': return ['Node', 'Network', 'Storage', 'CtrlPlane'];
    case 'network_troubleshooting': return ['Path', 'Firewall', 'NAT'];
    case 'database_diagnostics': return ['Query', 'Health', 'Schema', 'Synth'];
    default: return ['Agent'];
  }
};

const capabilityLabel = (cap?: string): string => {
  switch (cap) {
    case 'troubleshoot_app': return 'App';
    case 'pr_review': return 'PR';
    case 'github_issue_fix': return 'Issue';
    case 'cluster_diagnostics': return 'K8s';
    case 'network_troubleshooting': return 'Network';
    case 'database_diagnostics': return 'DB';
    default: return '';
  }
};

const capabilityIcon = (cap?: string): string => {
  switch (cap) {
    case 'troubleshoot_app': return 'troubleshoot';
    case 'pr_review': return 'rate_review';
    case 'github_issue_fix': return 'auto_fix_high';
    case 'cluster_diagnostics': return 'deployed_code';
    case 'network_troubleshooting': return 'route';
    case 'database_diagnostics': return 'database';
    default: return 'memory';
  }
};

const computeDuration = (created: string, updated: string): string => {
  const ms = new Date(updated).getTime() - new Date(created).getTime();
  if (ms < 60000) return `${Math.round(ms / 1000)}s`;
  return `${Math.round(ms / 60000)}m`;
};

const COMPLETED_PHASES = ['complete', 'diagnosis_complete', 'error'];

const LiveIntelligenceFeed: React.FC<LiveIntelligenceFeedProps> = ({
  onSelectSession,
  filterActive = false,
}) => {
  const { data: sessions = [], isLoading, isError } = useQuery({
    queryKey: ['live-sessions'],
    queryFn: listSessionsV4,
    refetchInterval: 10000,
    staleTime: 5000,
  });

  const displaySessions = useMemo(
    () => filterActive
      ? sessions.filter((s) => !COMPLETED_PHASES.includes(s.status))
      : sessions,
    [sessions, filterActive]
  );

  const handleDownloadReport = useCallback(async (session: V4Session) => {
    try {
      const { dossier, fixes } = await getSessionDossier(session.session_id);
      if (!dossier) return;
      const exec = dossier.executive_summary || {};
      const rca = dossier.root_cause_analysis || {};
      const md = [
        `# Diagnostic Report: ${session.service_name}`,
        `**Status:** ${exec.health_status || 'unknown'} | **Findings:** ${exec.total_findings || 0} | **Critical:** ${exec.critical_count || 0}`,
        ``,
        `## Root Cause`,
        `**${rca.primary_root_cause || 'N/A'}** (${rca.severity || '?'}, confidence: ${((rca.confidence || 0) * 100).toFixed(0)}%)`,
        rca.detail || '',
        ``,
        `## Evidence`,
        ...(dossier.evidence_chain || []).map((e: any, i: number) => `${i + 1}. **${e.title}** (${e.severity}) — ${e.detail || ''}`),
        ``,
        `## Recommended Fixes`,
        ...(fixes || []).map((f: any, i: number) => [
          `### ${i + 1}. ${f.title} (${f.severity})`,
          f.recommendation || '',
          f.sql ? `\`\`\`sql\n${f.sql}\n\`\`\`` : '',
        ].join('\n')),
        ``,
        `---`,
        `*Generated by DebugDuck*`,
      ].join('\n');
      const blob = new Blob([md], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `report-${session.session_id.slice(0, 8)}.md`;
      a.click();
      URL.revokeObjectURL(url);
    } catch { /* silent */ }
  }, []);

  return (
    <>
      {isLoading && displaySessions.length === 0 ? (
        <div className="space-y-2 p-2">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-16 rounded-md bg-duck-surface animate-pulse" style={{ opacity: 1 - i * 0.3 }} />
          ))}
        </div>
      ) : isError && !isLoading ? (
        <div className="flex flex-col items-center justify-center h-64 text-center">
          <span className="material-symbols-outlined text-4xl text-red-500 mb-3" aria-hidden="true">wifi_off</span>
          <p className="text-sm font-semibold text-slate-300 mb-1">Feed Disconnected</p>
          <p className="text-xs text-slate-400">Failed to sync with the intelligence server. Retrying...</p>
        </div>
      ) : displaySessions.length === 0 ? (
        <div className="flex flex-col items-center justify-center h-full py-12">
          {/* Ambient status display */}
          <div className="relative mb-6">
            <div className="w-20 h-20 rounded-full border-2 border-duck-border/30 flex items-center justify-center">
              <div className="w-14 h-14 rounded-full border border-duck-accent/20 flex items-center justify-center">
                <span className="material-symbols-outlined text-3xl text-duck-accent/40" aria-hidden="true">radar</span>
              </div>
            </div>
            {/* Scanning ring animation */}
            <div className="absolute inset-0 rounded-full border border-duck-accent/10 animate-ping" style={{ animationDuration: '3s' }} />
          </div>
          <p className="text-sm font-display font-bold text-slate-300 mb-1">
            {filterActive ? 'No Active Investigations' : 'Systems Monitored'}
          </p>
          <p className="text-xs text-slate-400 mb-4 text-center max-w-xs">
            {filterActive
              ? 'Start an investigation from Launch Control above.'
              : 'All systems are being monitored. Launch an investigation when an issue is detected.'}
          </p>
          {!filterActive && (
            <div className="flex items-center gap-3 text-body-xs text-slate-400">
              <span className="flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500/40" aria-hidden="true" />
                Monitoring
              </span>
              <span className="flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-duck-accent/40 animate-pulse" aria-hidden="true" />
                Ready
              </span>
            </div>
          )}
        </div>
      ) : (
        displaySessions.slice(0, 15).map((session) => {
          const { status, label } = phaseToStatus(session.status);
          const duration = computeDuration(session.created_at, session.updated_at);
          const timestamp = new Date(session.created_at).toLocaleTimeString([], {
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
          });

          return (
            <ActivityFeedRow
              key={session.session_id}
              targetService={session.service_name}
              incidentId={session.incident_id}
              timestamp={timestamp}
              status={status}
              phase={label}
              confidenceScore={Math.round(session.confidence)}
              durationStr={duration}
              capabilityIcon={capabilityIcon(session.capability)}
              isComplete={COMPLETED_PHASES.includes(session.status)}
              findingsCount={session.findings_count}
              criticalCount={session.critical_count}
              capability={session.capability}
              onClick={() => onSelectSession(session)}
              onViewReport={() => handleDownloadReport(session)}
            />
          );
        })
      )}
    </>
  );
};

export default LiveIntelligenceFeed;
