{{- include "aitsh.validate" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aitsh.serviceAccountName" . }}
  labels:
    {{- include "aitsh.labels" . | nindent 4 }}
{{- if .Values.image.pullSecret }}
imagePullSecrets:
  - name: {{ .Values.image.pullSecret }}
{{- end }}
