{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector: {matchLabels: {app: {{ .Values.name }}}}
  namespaceSelector: {matchNames: [{{ .Values.namespace }}]}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
